### ISSUE TITLE
Fix: Beneficiary and Holder UI components load forever if token owner is not a Title Escrow

### ISSUE THREAD

**Issue by rjchow** [TradeTrust/tradetrust-website#179]
![image](https://user-images.githubusercontent.com/27843274/86880011-a46ce100-c11e-11ea-8682-5a5f06eda1eb.png)

To reproduce:

[ebl-with-qrcode.txt](https://github.com/TradeTrust/tradetrust-website/files/4888622/ebl-with-qrcode.txt)

**Comment by yehjxraymond** [comment]
![image](https://user-images.githubusercontent.com/7406870/90354022-875ef280-e07a-11ea-93cf-b39d5c390331.png)

**Comment by yehjxraymond** [comment]
Issue id now gone when address is the token registry itself, but still persist when held by EOA
