### ISSUE TITLE
Unable to connect to TradeTrustErc721Factory using the Signer (wallet in ethers)

### ISSUE THREAD

**Issue by MidhunKRaj** [TradeTrust/tradetrust-website#223]
I have been working on the token registry integration in which I used the Signer(both based on private key and on mnemonics). I am getting an invalid message when I tried using the ethers. It was successful in the document verification process with the document store. Please check the attached image for the further details about the error. Kindly respond as soon as possible.

<img width="735" alt="trade trust issue" src="https://user-images.githubusercontent.com/45687173/91255274-0e4e5200-e782-11ea-98d8-aecef00118d8.png">

**Comment by yehjxraymond** [comment]
Check that your ethers version is v5.

**Comment by yehjxraymond** [comment]
Also, your private key is not so private anymore

**Comment by MidhunKRaj** [comment]
> Check that your ethers version is v5.
Thanks for your comment.
My ethers version is 6.13.7. Will that be a problem?

**Comment by yehjxraymond** [comment]
The latest version is only 5.0.9 .... 
https://www.npmjs.com/package/ethers
