### ISSUE TITLE
iphone 5//6/7  view is distorted 

### ISSUE THREAD

**Issue by sumitnitsurat** [TradeTrust/tradetrust-website#23]
discussed in #22

<img width="758" alt="Screenshot 2019-10-21 at 5 57 57 PM" src="https://user-images.githubusercontent.com/12955874/67197396-4af94080-f42f-11e9-958d-6bd82ee16de3.png">

**Comment by cavacado** [comment]
this is probably stale so closing it.

**Comment by cavacado** [comment]
![www tradetrust io_(iPhone 6_7_8)](https://user-images.githubusercontent.com/21698179/124426416-98047e00-dd9c-11eb-8934-d640874eef58.png)
