### ISSUE TITLE
bug: Direct transferTo call can cause an error in the Endorsement Chain

### ISSUE THREAD

**Issue by marlowl** [TradeTrust/tradetrust-website#283]
**Description:**
The [following](https://github.com/Open-Attestation/token-registry/blob/master/contracts/TitleEscrow.sol#L142) call can cause the Endorsement Chain to break.

**How to reproduce:**
- Execute a direct token transfer on a eBL with the [following](https://github.com/Open-Attestation/token-registry/blob/master/contracts/TitleEscrow.sol#L142) call
- Upload the eBL in the tradetrust site
- View Endorsement Chain
- The following will show up:

![Screenshot from 2020-11-25 12-14-40](https://user-images.githubusercontent.com/30845815/100225163-143d0600-2f1e-11eb-9b84-9ecb84aed96f.png)

I can also provide you with the .tt I used, if that is easier?

I did look at the [code](https://github.com/TradeTrust/tradetrust-website/blob/master/src/common/hooks/useEndorsementChain/useEndorsementChain.ts), and noticed that it looks for the following three states: Transfer, Surrender, Burnt. Only when the  [following](https://github.com/Open-Attestation/token-registry/blob/master/contracts/TitleEscrow.sol#L142) call is used, then it is not reaching either of those three states, resulting in the error.

**Possible solution:**
Support a state of the direct token transfer call in the Endorsement Chain

Came across this by chance, thought this might be helpful!

**Comment by dhemutton** [comment]
Hi @marlowl ,

Thank you for your feedback! I am looking into the issue and will get back to you soon😊
