### ISSUE TITLE
Implementation of the Corda Branch 

### ISSUE THREAD

**Issue by alokrajiv** [TradeTrust/tradetrust-website#322]
Hi Team,

This is the base issue that I wanted to open up as a primary channel for communication regarding our PR (reference from Shujing LIEW). Do let us know if there is a specific `CONTRIBUTING.md` or general guidelines in the Netlify/Readme.md, because we couldn't find it on master or on wiki.

So, what we did is to try and mirror the existing repo styles and pass your lint tests. Do let us know if anything to look out for, we will open the PR to `corda-dev` branch from our repo soon :) 

If you have a gitter/rocketchat channel, we are open to chat there too. If not, we will put in any questions we have in the thread below.

Regards,
Alok.

**Comment by Nebulis** [comment]
we have spectrum / github discussion

**Comment by alokrajiv** [comment]
Thanks @Nebulis , We have opened up a Discussion https://github.com/TradeTrust/tradetrust-website/discussions/324

**Comment by alokrajiv** [comment]
closing in favor of https://github.com/TradeTrust/tradetrust-website/discussions/324 .
