### ISSUE TITLE
Issuer Identity not valid

### ISSUE THREAD

**Issue by mayurtntra** [TradeTrust/tradetrust-website#359]
I have created the demo DNS to the "Rinkeby" network. I checked in google DNS for my demo DNS and my DNS is there with the TXT record. But when I use this DNS to issue the document on blockchain and try to verify my document, it shows that this DNS is not valid.

I am using the "TradeTrust" API to verify the document.
https://api-rinkeby.tradetrust.io/verify
This response is ' "issuerIdentity": false'.

Also, I have reported this issue on "Open-Attestation". Below this the link.
https://github.com/Open-Attestation/open-attestation-cli/issues/132

I tested the TT file from your website but it's not working. Please let me know. Is there any specific issue in TradeTrust or this is about the other.
https://rinkeby.tradetrust.io/

I have attached the DNS result of google.

![Query_ smooth-c](https://user-images.githubusercontent.com/52620062/119663456-fb22fc80-be4f-11eb-813f-947946cba987.png)

**Comment by simboonlong** [comment]
should be fixed now with https://github.com/Open-Attestation/oa-functions/pull/31
