### ISSUE TITLE
A tilte escrow contract can not issue multiple transferable documents.

### ISSUE THREAD

**Issue by bob-fly** [TradeTrust/tradetrust-website#385]
When we issue multiple transferrable documents in a single Escrow Contract, error below occurs.

`error     cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0xfB669973b373ebdad9Ded171848147728528C76D","gasPrice":{"type":"BigNumber","hex":"0x3b9aca00"},"to":"0xcf76c008671FF8A2057Ce830E8Bcfb6443F17173","data":"0xa144819400000000000000000000000060c0a7dac63d95d6e2ee13118ebbd22be2ac7820fd106cf08535a8e41140b49b694f93a79873799fef080f81786bb1860abe8b98","accessList":null}}, tx={"data":"0xa144819400000000000000000000000060c0a7dac63d95d6e2ee13118ebbd22be2ac7820fd106cf08535a8e41140b49b694f93a79873799fef080f81786bb1860abe8b98","to":{},"gasPrice":{"type":"BigNumber","hex":"0x3b9aca00"},"from":"0xfB669973b373ebdad9Ded171848147728528C76D","nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.3.0)`

**Comment by rjchow** [comment]
That’s intended, by design a TitleEscrow must only ever be used once for easier record keeping.

However we have an upcoming major release where TitleEscrows will be proxy contracts so the deployment costs will be hugely minimised.

**Comment by bob-fly** [comment]
> That’s intended, by design a TitleEscrow must only ever be used once for easier record keeping.
> 
> However we have an upcoming major release where TitleEscrows will be proxy contracts so the deployment costs will be hugely minimised.

Thank you, richow! You mean I must to redeploy the TitleEscrow contract when i issue a new transferable document every time when i use the current version of Open-attestation.?

**Comment by rjchow** [comment]
Indeed, in fact a new instance must be deployed every ownership change (assuming it is required)

**Comment by bob-fly** [comment]
> Indeed, in fact a new instance must be deployed every ownership change (assuming it is required)

Could you explain the purpose about this contract design?

**Comment by bob-fly** [comment]
> Indeed, in fact a new instance must be deployed every ownership change (assuming it is required)

I have already run the process of ownership transfer on the https://dev.tradetrust.io without deploy a new instance.

**Comment by rjchow** [comment]
> Could you explain the purpose about this contract design?

It is easier to determine the endorsement chain of an asset with this design where the ownership is immutable. (Yes it can also be retrieved from history but that introduces additional complications which requires your selected Ethereum node to be an archival node)

> I have already run the process of ownership transfer on the https://dev.tradetrust.io without deploy a new instance.

That's because we do it automatically in the transaction :)

**Comment by bob-fly** [comment]
> > Could you explain the purpose about this contract design?
> 
> It is easier to determine the endorsement chain of an asset with this design where the ownership is immutable. (Yes it can also be retrieved from history but that introduces additional complications which requires your selected Ethereum node to be an archival node)
> 
> > I have already run the process of ownership transfer on the https://dev.tradetrust.io without deploy a new instance.
> 
> That's because we do it automatically in the transaction :)

I had read the solidity and got it, thanks!
