### ISSUE TITLE
Import of address book csv file can not work 

### ISSUE THREAD

**Issue by bob-fly** [TradeTrust/tradetrust-website#386]
I downloaded the template file and input necessary information about ethereum account, then i upload the file, system can't not work. When I change the sequence of two columns, then it works.

![image](https://user-images.githubusercontent.com/15648863/123939885-35da0080-d9cb-11eb-8c66-523c06d18867.png)

**Comment by simboonlong** [comment]
can attach a sample file?

**Comment by bob-fly** [comment]
[template (1).csv](https://github.com/TradeTrust/tradetrust-website/files/6751985/template.1.csv)

bugfix solution
1) change the suffix of download template file with ".csv"
2) change the sequence of two columns

**Comment by simboonlong** [comment]
was not able to replicate the error with the attached sample file `template (1).csv`, is that the right one?

currently:
1. template downloaded already has suffix .csv, are you getting without?
2. manually changing of sequence works either way, or would u prefer the template file to follow what is the UI suggestng -> `Identifier` as first column then `Address` as second?

**Comment by bob-fly** [comment]
I have retried and it is fixed, thanks.
