### ISSUE TITLE
Manage Asset PR issues 

### ISSUE THREAD

**Issue by sumitnitsurat** [TradeTrust/tradetrust-website#60]
PR https://github.com/TradeTrust/tradetrust-website/pull/55

- [ ] Remove etherscan link from "Manage Asset"
- [ ] Move TokenSidebar at Parent level in DOM tree. Separate Asset info from TokenSidebar.
- [ ] Move state computation in TokenSidebar and rename it TokenSideBarContainer.
- [ ] Refactor TokenSidebar to handle open/close sidebar and display components.
- [ ] The TokenSideBarHolder should handle it's own state of the inputs. Think about how to put TokenSideBarHolder in a storybook, it will not be able to handle input changes.
- [ ] toggle implies that is doesnt need a param. Will be better to call this setActionLoader
- [ ] Thinking that the visibility should be handled in each of these sections independently. That way, we can leave the big chunk of logic out here. (Can discuss about it)
- [ ] Refactor components to 
        transferHoldership
        changeBeneficiary
        surrenderDocument

- [ ] encapsulated iniliazing token instnce so that we don't introduce bugs down the line (service/token.js)

- [ ] use await async for getAccounts service.
- [ ] adminAddress -> userWalletAddress
- [ ] export userwallter from ethersjs. add in index.js.
- [ ] put error as a parameter to setIsEscrowContractError
- [ ] transferStatus -> transactionHash in saga response.

**Comment by justussoh** [comment]
@rjchow  has this issue been solved?
