### ISSUE TITLE
Verify (Revoked) to have more descriptive text

### ISSUE THREAD

**Issue by HanXJ-Dev** [TradeTrust/tradetrust-website#676]
Hi there!
Currently, after revoking a document and verifying it, it displays the message of 
"Whoops! It's not you, it's us"
as shown in the attached image.

![image](https://user-images.githubusercontent.com/83289340/212613532-5fcec642-6b31-4a9d-a266-ebe6b0aaf691.png)

Wondering if there could be an update to reflect a more accurate message for revoked documents to follow OpenCerts
Where it displays
"Certificate has been revoked"

![image](https://user-images.githubusercontent.com/83289340/212613714-46d1e498-b566-42b3-9b85-1d1487aebeb2.png)

Thanks in advance!

**Comment by simboonlong** [comment]
can i clarify if the document revoked is via document store or ocsp responder?

**Comment by HanXJ-Dev** [comment]
Document store

**Comment by cavacado** [comment]
if its possible, could you provide the document used (or produce a minimal reproduction) so that we could try to debug it?

**Comment by HanXJ-Dev** [comment]
Hi @cavacado, thanks for the response, due to confidentiality issues, I can't share the document over Github, do let me know if there is an avenue for me to share it with you privately. 

As for reproduction of the issue, first the document is signed using `open-attestation sign` cli function and this would allow us to verify the document on https://dev.tradetrust.io/verify 
<img width="890" alt="image" src="https://user-images.githubusercontent.com/83289340/213419302-402bc50e-f3f6-4cec-bbce-585511d77000.png">

The revocation type of the document is set to `REVOCATION_STORE` with the location being the document store address that is deployed onto the GOERLI network.

To revoke, the CLI command `open-attestation document-store --network goerli revoke --address <document-store-add> --hash <merkle-root> -encrypted-wallet-path <path>` is ran, and upon trying to verify the same document again, this will be the screen shown.

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/83289340/213420832-41ce698e-8b9f-4517-a347-7fcf9a3f6412.png">

Please do let me know if there are any more information that I can provide thanks once again!

**Comment by cavacado** [comment]
Hi @HanXJ-Dev, thanks for writing up a detailed report.

Just to clarify abit, this document is identified by an ethr DID, and you are using a document store to store the revoked hash for this particular document?

One more thing you can do to help me is to paste the output of the document using this tool.
https://toolkit.openattestation.com/verify

**Comment by HanXJ-Dev** [comment]
@cavacado 
Yes, it is identified by ethr DID and we are using a document store to store the revoked hash
This is the output:
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/83289340/213632139-5354522d-22ff-41cc-a494-01df60d1d4c9.png">

```json
[
  {
    "type": "DOCUMENT_INTEGRITY",
    "name": "OpenAttestationHash",
    "data": true,
    "status": "VALID"
  },
  {
    "status": "SKIPPED",
    "type": "DOCUMENT_STATUS",
    "name": "OpenAttestationEthereumTokenRegistryStatus",
    "reason": {
      "code": 4,
      "codeString": "SKIPPED",
      "message": "Document issuers doesn't have \"tokenRegistry\" property or TOKEN_REGISTRY method"
    }
  },
  {
    "status": "SKIPPED",
    "type": "DOCUMENT_STATUS",
    "name": "OpenAttestationEthereumDocumentStoreStatus",
    "reason": {
      "code": 4,
      "codeString": "SKIPPED",
      "message": "Document issuers doesn't have \"documentStore\" or \"certificateStore\" property or DOCUMENT_STORE method"
    }
  },
  {
    "name": "OpenAttestationDidSignedDocumentStatus",
    "type": "DOCUMENT_STATUS",
    "data": {
      "issuedOnAll": true,
      "revokedOnAny": true,
      "details": {
        "issuance": [
          {
            "issued": true,
            "did": "did:ethr:<address>"
          }
        ],
        "revocation": [
          {
            "revoked": true,
            "address": "<address>",
            "reason": {
              "message": "Document<merkle-root> has been revoked under contract <contract>",
              "code": 5,
              "codeString": "DOCUMENT_REVOKED"
            }
          }
        ]
      }
    },
    "status": "INVALID",
    "reason": {
      "message": "Document <merkle-root> has been revoked under contract <contract>",
      "code": 5,
      "codeString": "DOCUMENT_REVOKED"
    }
  },
  {
    "status": "SKIPPED",
    "type": "ISSUER_IDENTITY",
    "name": "OpenAttestationDnsTxtIdentityProof",
    "reason": {
      "code": 2,
      "codeString": "SKIPPED",
      "message": "Document issuers doesn't have \"documentStore\" / \"tokenRegistry\" property or doesn't use DNS-TXT type"
    }
  },
  {
    "name": "OpenAttestationDnsDidIdentityProof",
    "type": "ISSUER_IDENTITY",
    "data": [
      {
        "location": <location>,
        "key": "did:ethr:<address>#controller",
        "status": "VALID"
      }
    ],
    "status": "VALID"
  }
]
```
