### ISSUE TITLE
TradeTrust doesn't verify example OpenAttestation v3 documents

### ISSUE THREAD

**Issue by morgatron** [TradeTrust/tradetrust-website#701]
TradeTrust doesn't appear to verify the test fixtures from oa-verify, in particular I've tried the OA-v3 examples. The reason seems to be the lack of a `network` field in those docs. Is this expected behaviour?

In OpenAttestation, it appears that `network` is supposed to be optional. Is it supposed to be required in TradeTrust?

**Comment by cavacado** [comment]
Hey @morgatron. Thanks for opening this issue.
No, the `network` field is optional and should not impact the validity of the documents. Its main functionality is to prompt a user to swap his/her network to the document's one on metamask if he/she is on a different network. 
see [here](https://github.com/TradeTrust/tradetrust-website/blob/c95d029cc0fbe778cee0fcafb3f95fdffa8341c2/src/utils/shared.ts#L43)

In particular which test fixture from `oa-verify` were you trying to use to verify?

I would not recommend using the test-fixtures from `oa-verify` to verify, as most of them were really created to test the functionality of `oa-verify` and not the other components surrounding them.
for eg: [this document](https://github.com/Open-Attestation/oa-verify/blob/master/test/fixtures/v3/documentStore-issued.json) has dummy attachments, and thus will fail/throw an unexpected error on tt-website.

Instead, I would recommend using tt-website's own test fixtures to test your assumptions.

**Comment by morgatron** [comment]
Ahh, my apologies @cavacado, it appears you're right (and I should've used TradeTrusts's test fixtures)

We got to here because we were having trouble verifying our own issued odcs on TradeTrust, but looks like we were confused about the reason.

Thanks for the rapid reply.  Closing the issue...
