### ISSUE TITLE
Degraded performance and endorsement chain errors on dev.tradetrust.io for Mumbai network

### ISSUE THREAD

**Issue by marlowl** [TradeTrust/tradetrust-website#862]
We have observed degraded performance on dev.tradetrust.io when uploading TradeTrust (tt) files for the Mumbai network. After dragging & dropping or manually uploading a tt file, an error message occasionally appears. Clicking "OK" and retrying the upload sometimes resolves the issue, but not consistently.

![Screenshot 2024-01-23 105819](https://github.com/TradeTrust/tradetrust-website/assets/30845815/da06d59d-e36d-42c7-ac72-cf527326ec44)

**Endorsement Chain**  

Additionally, we are experiencing errors related to the endorsement chain on the Mumbai network. The specifics of the errors encountered are depicted in the attached screenshot.

![Screenshot 2024-01-23 110041](https://github.com/TradeTrust/tradetrust-website/assets/30845815/04d8f569-7f64-4b0a-a278-a0dcf88436b9)

I have attempted to address the problem by experimenting with different RPC providers for the Mumbai network, but unfortunately, this did not resolve the issue. Has anyone encountered similar issues before? Any insights or recommendations would be greatly appreciated! 😄

**Comment by marlowl** [comment]
Small update: 
For now, we have reverted to Sepolia, where everything continues to function as anticipated 😄 @superical

**Comment by isaackps** [comment]
Hi, 
Understand that there currently have this issue with testnet mumbai. 
We are still investigating the cause.
Will update once we found a solution to the problem, thanks.

**Comment by marlowl** [comment]
Thank you, @isaackps, for your response. We encountered some challenges with Mumbai RPC node instability in the past, unrelated to TradeTrust.

**Comment by tradetrustimda** [comment]
@marlowl with the deprecation of Mumbai, if you have any issue on Amoy, do open a new issue on it. Thanks.
