### ISSUE TITLE
Unable to verify the "Signed Document" in "Dev.tradetrust.io"

### ISSUE THREAD

**Issue by LogeswaranA** [TradeTrust/tradetrust-website#939]
Hi - 

I am trying to setup & integrate tradetrust into the trade flow platform. I followed this documentation to try out the samples provided in the documentation. 

https://docs.tradetrust.io/docs/tutorial/verifiable-documents/raw-document (raw document)
https://docs.tradetrust.io/docs/tutorial/verifiable-documents/wrapping-document/wrapping-document-cli - Wrapping using CLI
https://docs.tradetrust.io/docs/tutorial/verifiable-documents/signing-document/signing-document-cli -- Signing using CLI

The CLI command worked fine, and the signed document was created.

After these steps, I got the "Signed version document". As per the documentation, when I head over to "https://dev.tradetrust.io/verify" and try to verity the signed document, it is throwing below error.

"Document is not valid"

Whoops it is not you, It's Us

etc.

I am stuck with this issue, any direction to move forward would be helpful.

Thank you

**Comment by LogeswaranA** [comment]
It is working when we issue a wrapped document without signing. After wrapping the document, when you issue & verify, then it is working fine.

Is this expected results ?

**Comment by rongquan1** [comment]
@LogeswaranA 

Could you please provide the signed document? We’d like to test it on our end to ensure everything is working as expected.

**Comment by LogeswaranA** [comment]
Sure, please find the signed-version

[signed-doc.json](https://github.com/user-attachments/files/16686717/signed-doc.json)

Also, note that as per the doc it is nowhere mentioned that after "Sign document" it should be issued. So I haven't issued this document hash in the document store.

**Comment by rongquan1** [comment]
@LogeswaranA 

It looks like you have missed a step during the process. Please refer to this [documentation](https://docs.tradetrust.io/docs/tutorial/verifiable-documents/raw-document/#1-issuers0identityproofkey) and give it another try.

**Comment by LogeswaranA** [comment]
Thanks, I just tried the same but got a different error: 

"Document issuer identity is invalid
This document was issued by an invalid issuer."

Here is my signed doc and I ensured that my public wallet address & DNS are correct. please check.

Please note, that I am using the npm package to wrap & encrypt this time.

here is my code snippet :

const wrappedDocument = await wrapDocumentV2(coojson);
    console.log("wrappedDocument", wrappedDocument);
    const signedDocument = await signDocument(
      wrappedDocument,
      SUPPORTED_SIGNING_ALGORITHM.Secp256k1VerificationKey2018,
      {
        public: `did:ethr:${signer}#controller`,
        private: pkey,
      }
    );

[wrapped-signed.json](https://github.com/user-attachments/files/16687934/wrapped-signed.json)

**Comment by rongquan1** [comment]
@LogeswaranA 

We noticed that the DNS records are pointing to a different address instead. Please follow the instructions in this [documentation](https://docs.tradetrust.io/docs/tutorial/verifiable-documents/dns) and try again.

**Comment by LogeswaranA** [comment]
yes thank you so much, now it works, I followed the CLI method from the beginning again and it worked.

thank you @rongquan1 

Sorry for the false alarm!!
